### ISSUE TITLE
Using in Angular

### ISSUE THREAD

**Issue by rhanb** [kobby-sun/nativescript-bottomnavigation#3]
Hi,

This plugin is exactly what I need but I can't make it work with Angular even when regisetering Element, could you provide an example?

Thanks

**Comment by taibuiSW** [comment]
Hi, have you figured it out? If you have, please teach me

**Comment by rhanb** [comment]
@taibuiSW since then I created my own plugin which you can find here:

https://github.com/rhanb/nativescript-bottombar

**Comment by taibuiSW** [comment]
Oh, your plugin was the one I tried after that. Work like a charm! Best bottombar I've tried so far. Thank you :+1:
